package woo.daykey.model;
// Generated 2018. 2. 6 ���� 2:53:23 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "news", catalog = "daykey")
public class News implements java.io.Serializable {

	private int url;
	private String title;
	private String teacher;
	private String visitors;
	private String date;

	public News() {
	}

	public News(int url) {
		this.url = url;
	}

	public News(int url, String title, String teacher, String visitors, String date) {
		this.url = url;
		this.title = title;
		this.teacher = teacher;
		this.visitors = visitors;
		this.date = date;
	}

	@Id

	@Column(name = "url", unique = true, nullable = false)
	public int getUrl() {
		return this.url;
	}

	public void setUrl(int url) {
		this.url = url;
	}

	@Column(name = "title", length = 65535)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "teacher", length = 10)
	public String getTeacher() {
		return this.teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

	@Column(name = "visitors", length = 65535)
	public String getVisitors() {
		return this.visitors;
	}

	public void setVisitors(String visitors) {
		this.visitors = visitors;
	}

	@Column(name = "date", length = 65535)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}
