package woo.daykey.model;
// Generated 2018. 2. 6 ���� 2:53:23 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "schedule", catalog = "daykey")
public class Schedule implements java.io.Serializable {

	private Integer num;
	private String name;
	private int grade;
	private int class_;
	private int password;
	private String year;
	private String month;
	private String date;
	private String sche;
	private String email;
	private byte booleanPublic;

	public Schedule() {
	}

	public Schedule(String name, int grade, int class_, int password, String year, String month, String date,
			String sche, String email, byte booleanPublic) {
		this.name = name;
		this.grade = grade;
		this.class_ = class_;
		this.password = password;
		this.year = year;
		this.month = month;
		this.date = date;
		this.sche = sche;
		this.email = email;
		this.booleanPublic = booleanPublic;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "num", unique = true, nullable = false)
	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	@Column(name = "name", nullable = false, length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "grade", nullable = false)
	public int getGrade() {
		return this.grade;
	}

	public void setGrade(int grade) {
		this.grade = grade;
	}

	@Column(name = "class", nullable = false)
	public int getClass_() {
		return this.class_;
	}

	public void setClass_(int class_) {
		this.class_ = class_;
	}

	@Column(name = "password", nullable = false)
	public int getPassword() {
		return this.password;
	}

	public void setPassword(int password) {
		this.password = password;
	}

	@Column(name = "year", nullable = false, length = 65535)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "month", nullable = false, length = 65535)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "date", nullable = false, length = 65535)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "sche", nullable = false, length = 65535)
	public String getSche() {
		return this.sche;
	}

	public void setSche(String sche) {
		this.sche = sche;
	}

	@Column(name = "email", nullable = false, length = 65535)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "boolean_public", nullable = false)
	public byte getBooleanPublic() {
		return this.booleanPublic;
	}

	public void setBooleanPublic(byte booleanPublic) {
		this.booleanPublic = booleanPublic;
	}

}
